name: Build & Testing distribute

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - run: npm install

      - name: ncc build
        run: |
          npx @vercel/ncc build src/main.ts

  Test:
    runs-on: ubuntu-latest
    needs: Build
    timeout-minutes: 5
    strategy:
      matrix:
        dirs: ['0', '1', '2', '3']

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: unity-get-version
        with:
          project-directory: ${{ github.workspace }}/unity/${{ matrix.dirs }}

      - name: echo Unity version
        env:
          VERSION: ${{ steps.unity-get-version.outputs.version }}
        run: |
          echo $VERSION
