name: Test

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dirs: ['0', '1', '2', '3']

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: unity-get-version
        with:
          project-directory: ${{ github.workspace }}/unity/${{ matrix.dirs }}

      - name: echo Unity version
        env:
          VERSION: ${{ steps.unity-get-version.outputs.version }}
        run: |
          echo $VERSION
